<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="raman-Vostro-3578" failures="1" tests="1" name="Test" time="31.375" errors="0" timestamp="2022-12-26T17:19:49 IST">
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="31.014">
    <failure type="java.lang.IndexOutOfBoundsException" message="Index 1 out of bounds for length 1">
      <![CDATA[java.lang.IndexOutOfBoundsException: Index 1 out of bounds for length 1
at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
at java.base/java.util.Objects.checkIndex(Objects.java:359)
at java.base/java.util.ArrayList.get(ArrayList.java:427)
at amazonSteps.amazonSteps.verify_user_navigation_to_about_this_item_section(amazonSteps.java:48)
at âœ½.Verify user navigation to About this item section(classpath:amazonSteps/amazon.feature:7)
]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- Test -->
